import type { Metadata } from "next";

import "./globals.css";
import { Toaster } from "react-hot-toast";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { GoogleOAuthProvider } from "@react-oauth/google";
import ReactQueryProvider from "./QueryClientProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <GoogleOAuthProvider clientId="119713032631-cq98fi2ldl90cjkg0se21uqhen0odk72.apps.googleusercontent.com">
          <body className="font-sans">{children}</body>
          <Toaster />
          <ReactQueryDevtools />
        </GoogleOAuthProvider>
      </ReactQueryProvider>
    </html>
  );
}
